/* tslint:disable */
/* eslint-disable */
/**
 * Roast Advisor API
 * Returns reviews of Sunday roasts
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * The comment associated with the review
     * @type {string}
     * @memberof Review
     */
    comment: string;
    /**
     * Unique internal ID of the incident debrief
     * @type {string}
     * @memberof Review
     */
    id: string;
    /**
     * ID of the user who left the review
     * @type {string}
     * @memberof Review
     */
    userId: string;
}

/**
 * Check if a given object implements the Review interface.
 */
export function instanceOfReview(value: object): value is Review {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
        'id': json['id'],
        'userId': json['user_id'],
    };
}

export function ReviewToJSON(value?: Review | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comment': value['comment'],
        'id': value['id'],
        'user_id': value['userId'],
    };
}

