/* tslint:disable */
/* eslint-disable */
/**
 * Roast Advisor API
 * Returns reviews of Sunday roasts
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Review,
} from '../models/index';
import {
    ReviewFromJSON,
    ReviewToJSON,
} from '../models/index';

/**
 * 
 */
export class ReviewsApi extends runtime.BaseAPI {

    /**
     * List all reviews.
     * List Reviews
     */
    async reviewsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Review>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/reviews`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReviewFromJSON));
    }

    /**
     * List all reviews.
     * List Reviews
     */
    async reviewsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Review>> {
        const response = await this.reviewsListRaw(initOverrides);
        return await response.value();
    }

}
