openapi: 3.0.3
info:
    title: Roast Advisor API
    description: Returns reviews of Sunday roasts
    version: 0.0.1
servers:
    - url: http://localhost:8000
paths:
    /reviews:
        get:
            tags:
                - Reviews
            summary: List Reviews
            description: List all reviews.
            operationId: Reviews#List
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Review'
                                example:
                                    - id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                      restaurant_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                      user_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                    - id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                      restaurant_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                      user_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                    - id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                      restaurant_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                      user_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                            example:
                                - id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                  restaurant_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                  user_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                - id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                  restaurant_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                  user_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                - id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                  restaurant_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                                  user_id: 01G0J1EXE7AXZ2C93K61WBPYEH
components:
    schemas:
        Review:
            type: object
            properties:
                id:
                    type: string
                    description: Unique internal ID of the incident debrief
                    example: 01G0J1EXE7AXZ2C93K61WBPYEH
                restaurant_id:
                    type: string
                    description: ID of the restaurant the review is for
                    example: 01G0J1EXE7AXZ2C93K61WBPYEH
                user_id:
                    type: string
                    description: ID of the user who left the review
                    example: 01G0J1EXE7AXZ2C93K61WBPYEH
            example:
                id: 01G0J1EXE7AXZ2C93K61WBPYEH
                restaurant_id: 01G0J1EXE7AXZ2C93K61WBPYEH
                user_id: 01G0J1EXE7AXZ2C93K61WBPYEH
            required:
                - id
                - user_id
                - restaurant_id
tags:
    - name: Reviews
      description: The reviews service provides operations to manage reviews.
