// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/reviews": {
            "get": {
                "description": "Responds with the list of all reviews as JSON.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get array of reviews",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Review"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Review": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "ratingAddOns",
                "ratingMeat",
                "ratingPotatoes",
                "ratingPrice",
                "ratingSize",
                "ratingVeg",
                "restaurantID",
                "updatedAt",
                "userID"
            ],
            "properties": {
                "archivedAt": {
                    "type": "string"
                },
                "commentAddOns": {
                    "type": "string"
                },
                "commentMeat": {
                    "type": "string"
                },
                "commentPotatoes": {
                    "type": "string"
                },
                "commentPrice": {
                    "type": "string"
                },
                "commentSize": {
                    "type": "string"
                },
                "commentVeg": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ratingAddOns": {
                    "type": "integer"
                },
                "ratingMeat": {
                    "type": "integer"
                },
                "ratingPotatoes": {
                    "type": "integer"
                },
                "ratingPrice": {
                    "type": "integer"
                },
                "ratingSize": {
                    "type": "integer"
                },
                "ratingVeg": {
                    "type": "integer"
                },
                "restaurantID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Roast Advisor API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
