definitions:
  domain.Review:
    properties:
      archivedAt:
        type: string
      commentAddOns:
        type: string
      commentMeat:
        type: string
      commentPotatoes:
        type: string
      commentPrice:
        type: string
      commentSize:
        type: string
      commentVeg:
        type: string
      createdAt:
        type: string
      id:
        type: string
      ratingAddOns:
        type: integer
      ratingMeat:
        type: integer
      ratingPotatoes:
        type: integer
      ratingPrice:
        type: integer
      ratingSize:
        type: integer
      ratingVeg:
        type: integer
      restaurantID:
        type: string
      updatedAt:
        type: string
      userID:
        type: string
    required:
    - createdAt
    - id
    - ratingAddOns
    - ratingMeat
    - ratingPotatoes
    - ratingPrice
    - ratingSize
    - ratingVeg
    - restaurantID
    - updatedAt
    - userID
    type: object
info:
  contact: {}
  title: Roast Advisor API
paths:
  /reviews:
    get:
      description: Responds with the list of all reviews as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Review'
            type: array
      summary: Get array of reviews
swagger: "2.0"
